version: '3.8'

services:
  postgres1:
    image: postgres:15.4
    container_name: postgres1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -U keycloak"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  postgres2:
    image: postgres:15.4
    container_name: postgres2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=disparos
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -U user"
    volumes:
      - ./postgres_spring:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    environment:
      - "KEYCLOAK_IMPORT= /opt/jboss/keycloak/imports/realm-export.json"
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres1
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_HEALTH_ENABLED=true
    ports:
      - "8443:8080"
    command: start-dev
    depends_on:
      - postgres1
    healthcheck:
      test: "curl -f http://localhost:8080/health/ready || exit 1"
    volumes:
      - ./imports/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
